package com.uniwork.enums;

public enum Role {
    OWNER,
    PROJECT_MANAGER,
    MEMBER,
    MOBILE_DEVELOPER,
    TESTER,
    IOT_ENGINEER,
    BA,
    DATA_ENGINEER,
    BACKEND_DEVELOPER,
    UIUX_DESIGNER,
    AI_ENGINEER,
    BI_ANALYST,
    FULLSTACK_DEVELOPER,
    DEVOPS,
    FRONTEND_DEVELOPER;
}
